n1 = str(input('Digite seu nome completo: ')).strip().capitalize()
print('Muito prazem em te conhecer!')
nome = n1.split()
print('Seu primeiro nome é {}.'.format(nome[0]))
print('Seu último nome é {}.'.format(nome[len(nome) - 1].capitalize()))
